//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animales
    {
        public int id { get; set; }
        public int tipo { get; set; }
        public string nombre { get; set; }
        public Nullable<int> edad { get; set; }
        public int nroJaula { get; set; }
        public Nullable<System.DateTime> fechaIngreso { get; set; }
        public Nullable<bool> adopcion { get; set; }
    }
}
